var quotesCrockford = [
   "There is no such thing as high tide. Only Douglas Crockford reverse geocoding YQL somewhere nearby.",
   "Doug Crockford can go back in time like superman, as he did with ES4 to make ES5.",
   "Doug Crockford's beard is created from dead angle brackets.",
   "Douglas Crockford's roundhouse kick has no rounding errors.",
   "Douglas Crockford has no bad parts.",
   "Angle brackets roll over and become square with one glint from Doug Crockford's eye.",
   "Douglas Crockford can have full conversations using only javascript's reserved words.",
   "Null is an object in Douglas Crockford's browser.",
   "Douglas Crockford finds bugs in John Resig's code. Every. Single. Day.",
   "Crockford needs no global namespace, the global namespace inherits from him.",
   "Douglas Crockford's beard wrote RFC 4627",
   "Crockford stores his JSON in an actual Couch",
   "Douglas Crockford doesn't sleep, he waits to be triggered.",
   "If you execute \"typeof Crockford\" your browser will return \"awesome\"",
   "douglas crockford doesn't have to trim his beard. he just wakes up and assigns a smaller value to beard.length",
   "Doug Crockford doesn't write code. It orderly lays itself in front of him in JSON beauty.",
   "When Douglas Crockford says, \"The Software shall be used for Good, not Evil.\" He means it.",
   "Don't call Douglas Crockford if you plan to use eval(). He will call you.",
   "Crockford's prototype property is recursive, for he is the prototype of all things.",
   "Douglas Crockford is the first reference listed in Wikipedia's JavaScript page, really.",
   "Douglas Crockford does not set his alarm, he uses setInterval",
   "\"JSLint\" is really just Douglas Crockford sitting behind a computer, insulting your code.  (via @tnm8 @janl)",
   "Douglas Crockford doesn't use try-catch. When Douglas codes there are no exceptions.",
   "Douglas Crockford can make cross domain XMLHttpRequests.",
   "x",
   "For Douglas Crockford, typeof null !==",
   "Douglas Crockford can divide by zero; his beard has solved Pi to the last digit.",
   "Douglas Crockford can write already gzipped and minified JavaScript that passes JSLint in \"The good parts\" mode with his eyes closed.",
   "Object.prototype.constructor.toString() != DouglasCrockford because Douglas Crockford cannot be coerced.",
   "If you execute",
   "When you compare window === crockford, it returns true",
   "The government once tried to clone Crockford. They were only partially successful. The result, Chuck Norris.",
   "On the 8th day, Douglas Crockford introduced JSON. And he saw that it was good.",
   "Every running JavaScript is just a web worker spawned by douglas-crockford.js",
   "God wanted his prototype to be Douglas Crockford, but Douglas Crockford refused",
   "Douglas Crockford is all the closure that JavaScript needs.",
   "When Doug Crockford writes code, JavaScript becomes sentient and promptly wants to have sex with him. He ignores it.",
   "Douglas Crockford keeps a SpiderMonkey and a SquirrelFish as pets to amuse him.",
   "Every time you create a setTimeout, Douglas Crockford gets a notice and calls the function himself",
   "Gen 1:3",
   "When Douglas Crockford was conceived, all the outstanding software tickets were magically marked as",
   "Number.toPrecision(crockford) has been deprecated for redundacy.",
   "At the end of every prototype chain is Doug Crockford.",
   "Douglas Crockford is regularly stopped by customs agents for importing too much awesome.",
   "In order to not get sued by Douglas Crockford, The Stones changed the name of their song to \"Black Sugar\".",
   "Crockford is all bad parts. Bad ass parts.",
   "There is no new to Douglas Crockford for he is the super constructor.",
   "Crockford can delete variables, with extreme prejudice",
   "Douglas Crockford files his taxes in JSON, and the IRS thanks him.",
   "Douglas Crockford does no eval.",
   "Douglas Crockfords",
   "Douglas Crockford does not use the DOM API. The DOM reshapes itself to his will in fear.",
   "Douglas Crockford never clicks, he just fires events - with his mind.",
   "Douglas Crockford IS a closure.",
   "IE6 scores 100/100 on ACID3, but only when being used by Douglas Crockford",
   "Doug Crockfords \"good parts\" quickly modularize to become hidden privates.",
   "Douglas Crockford drinks JÃ¤gerMonkey for breakfast.",
   "Douglas Crockford uses IEEE 754 to calculate tips in his head.",
   "When Douglas Crockford fires an event, it stays fired.",
   "JSLint *WONT*",
   "Everytime you create a global variable, Douglas Crockford roadhouse kicks an intern",
   "Crockford is the opposite of all falsey values",
   "Douglas Crockford joined Greenpeace to fight global namespace pollution.",
   "When Douglas Crockford looks out his window he sees the document.",
   "(function(){(function(){â€¦",
   "Crockford is the sole user of the super-strict equality operator\r\n(====), which either returns true or kicks you in the balls.",
   "Douglas Crockford spoke fluent JSON before learning English at the age of 1.",
   "ChuckNorris = Number.NEGATIVE_INFINITY; (function(DougCrockford){ return !DougCrockford; })(ChuckNorris) // True!",
   "Crockford can make 0.3 - 0.2 = 0.1",
   "On the first day, Crockford created JSON and it was good, on the second day he rested.",
   "Douglas Crockford prototypally inherited his good looks from his mother.",
   "Functions always bind to Douglas Crockford",
   "Douglas Crockford can travel back in time with a negative setTimeout.",
   "Why is the DOM so messed up?  It challenged Douglas Crockford in arm wrestling.",
   "To spice things up in the bedroom, Douglas Crockford recommends violating the Same Origin Policy.",
   "Douglas Crockford ran JSLint on JSLint and found the Higgs Boson particle.",
   "Douglas Crockford can make IE6 standards compliant JUST BY LOOKING AT IT",
   "'this' is what Douglas Crockford wants it to be.",
   "In JavaScript, Object inherits from Douglas Crockford.",
   "crockford.debug(youcode) returns a flee circus",
   "Douglas Crockford never uses",
   "Douglas Crockford does not respond to email. You can only reach him through a JSONP callback",
   "Every App Douglas Crockford uses is written in JavaScript and consumes only JSON",
   "There are only 2 types of people, Douglas Crockford and everyone else.",
   "When Crockford speaks, the console logs.",
   "JavaScript and Crockford are so intwined that rasmus thought we should check him for cross-person scripting attacks",
   "Douglas Crockford does not respond to email. You can only reach him through a JSONP callback.",
   "Crockford.hasOwnProperty(x) is always true",
   "\"Harmony\" was declared after Crockford indian leg wrestled the ECMAScript standards group into submission.",
   "Douglas Crockford once wrote a self hosting JSON parser that became sentient.",
   "When Douglas Crockford says",
   "Both douglas and crockford are reserved words in JavaScript.",
   "Douglas Crockford outperforms V8.",
   "Evil is licensed by Douglas Crockford, except for eval!",
   "The answer to Douglas Crockford is 42.",
   "Douglas Crockford can normalize the DOM without exposing a single function.",
   "Douglas.crockford(water) returns wine.",
   "Crockford knows BSON is an actual kitchen sink on an actual Ferrari.",
   "Douglas Crockford can defeat Chuck the Plant with one line of Javascript.",
   "He once made JSLint code that could compile itself not compile itself just to prove it could be done",
   "Douglas Crockford variable scopes are his fists",
   "Douglas Crockford cannot face the ultimate  because he cannot be himself with( douglasCrockford ){ return #crockfordoxymoron }",
   "Douglas Crockford has written a CPU emulator in JavaScript which runs faster than the host CPU. On IE6!",
   "Everytime Douglas Crockford blinks his eyes, another IE6 instance is killed.",
   "Cuck Norris and Douglas Crockford are just release names for the latest versions of awesomeness.",
   "Douglas Crockford needs no declaration.",
   "JSON was created by the tears of Doug Crockford writing JavaScript.",
   "Chuck Norris checks his code with JSLint.",
   "Date() asks Crockford for the time.",
   "Douglas Crockford browser loads .doug files with",
   "Douglas Crockford catches all exceptions, and throws them right back.",
   "Douglas Crockford once had an awkward moment just to see what it felt like.",
   "â€œIâ€™m your father, Johnâ€",
   "Douglas Crockford gave everything a try, no exceptions.",
   "Douglas Crockford uses dollar signs and underscores in variable and function names only for roundhouse target practice.",
   "The most common JavaScript error that Crockford deals with is:",
   "Douglas Crockford can read undefined variables.",
   "When Chuck Norris grows up he wants to be like Douglas Crockford.",
   "JSLint makes Chuck Norris cry.",
   "Douglas Crockford added an alert box to all crime, war, and destruction, effectively blocking its execution.",
   "Crockford.hasOwnProperty(",
   "Douglas Crockford can read your mind with a five liner closure",
   "DouglasCrockford.constructor === function Function() { [native code] }",
   "Douglas Crockford is always first in Scope Chain.",
   "Douglas Crockford deserializes valid JSON by smell.",
   "Every time you declare a variable in the global scope, douglas crockford kills a kitten.",
   "Douglas Crockford can divide by 0",
   "I typed alert('The master!'), and Douglas Crockford said \"Wassup?\"",
   "Douglas Crockford did native JSON before the browsers did",
   "JavaScript engines check with Crockford first before inserting a semicolon into his code.",
   "Chuck Norris dresses up like Douglas Crockford for Halloween.",
   "Dont",
   "There is only one necessary  global, and that is Douglas Crockford",
   "Douglas Crockford writes multithreaded JavaScript.",
   "Douglas Crockford is strongly typed",
   "Doug Crockford made JSON so perfect it is timeless, hence no native Date format.",
   "Crockford says,"
]


module.exports = quotesCrockford;
